version: "3"

services:
  http:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:cached
      - ./../src:/var/www/localhost
    links:
      - php

  php:
    build: php
    working_dir: /var/www/localhost
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php-override.ini
      - ./../src:/var/www/localhost

  db:
    image: mariadb:10.10.2
    working_dir: /var/www/localhost
    ports:
      - "3306:3306"
    volumes:
      - ./../src:/var/www/localhost
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8080:80"
    links:
      - db

volumes:
  dbdata: ~
